### ISSUE TITLE
README update

### ISSUE THREAD

**Issue by blockchainrelativity** [Mrpye/notion-export-cleaner#1]
Either I am incorrect or the documentation is. I was unable to run the code using the readme, but I discovered the command that did work for me was
 ```notion-export-cleaner clean "./zip" "./" ```
I would also recommend being a bit more aggressive on the requirements (go 1.8) as the latest go version does not work, and it seems lightly mentioned that 1.8 is needed. It was fairly deep in the archived versions of Go, so maybe even providing a URL to that version that is required would be helpful. 
Thanks for this tool! I cant believe Notion hasnt fixed this!

**Comment by blarghblurgh** [comment]
Also unable to run the code. System can't find the command` notion-export-cleaner`. Using latest Mac release of go (1.20.4).

**Comment by Mrpye** [comment]
Thanks for your feedback ill update

**Comment by Mrpye** [comment]
Updated the document and updated the go requirement  to 1.20

**Comment by Mrpye** [comment]
Glad you found the tool useful. Notion is a great tool but the guid string annoyed me especially when it made the file paths to long so you could not unzip then. hence this tool.  thank again for taking the time to report the issue
