### ISSUE TITLE
It seems that the character length of the guid has become 32 now

### ISSUE THREAD

**Issue by hassaannoor** [Mrpye/notion-export-cleaner#2]
![image](https://github.com/Mrpye/notion-export-cleaner/assets/67913635/6e1aa5fc-6a25-494e-8822-e489c86b9efd)

"Books 1a78ccd212f24e019a77ad171a8a572d.md"

You might have to change 36 to 32 in code.

**Comment by Mrpye** [comment]
Thanks for pointing this out ill take a look

**Comment by Mrpye** [comment]
It looks like I am already using the 32-length GUID
